# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: CV  
    url: "cv/"  
    weight: 30
  - name: Publications
    url: publications/
    weight: 40
  - name: Meditations
    url: meditations/
    weight: 50
   
